### ISSUE TITLE
Can't find dependency

### ISSUE THREAD

**Issue by daveloyall** [SamSkulls/breaker#1]
I can't find 'mutil' anywhere.  What is it?

FYI, I don't actually need a break timer.  I just needed a simple program that draws on screen via CLX... :)

**Comment by SamSkulls** [comment]
MUtil is one of my repos. (I should mention these things in the readme; thanks for the feedback.)


But as to your actual problem, you can see a CLX window in action here: https://github.com/stumpwm/stumpwm

Or a toy example here: http://rosettacode.org/wiki/Window_creation/X11#Common_Lisp

**Comment by daveloyall** [comment]
Thanks, Sam.  Yes, I am a stumpwm user.  Thanks for the link to the example!
